package com.crm.crmqueue.dto;

import java.util.Date;

public class OrderInfoBO {
	public float SaleOrderOnlineOld;
	SMSCoupon[] lstSMSCoupon;
	public int SHIPPACKAGETYPE;
	public int DayTranfer;
	public int TransportTypeID;
	public int StoreChangeOrderTypeID;
	public int TranferStoreID;
	public int LATITUDE;
	public int LNGTITUDE;
	public int DeliveryPackage;
	public String VOUCHERCONCERN;
	public String DEADTIME;
	public float PAYMENTONLINESTATUSID;
	public String STUDENTID;
	public String SCHOOLNAME;
	ProductWeb[] lstProductWeb;
	ProductGift[] lstProductGift;
	public int STEP;
	public String EMPLOYEENOTE;
	public String SYSTEMLOG;
	public String LstProductCodeSim;
	public boolean IsReviewSimCard;
	public Date EXPIREDTIME;
	public int DeviceID;
	public int TYPE;
	public int QUEUETYPE;
	public int IsInsurefee;
	public int ISAUTOTRANFERERP;
	public String CompanyName;
	public String CompanyAddress;
	public String CompanyTaxNo;
	public int COUNTMINUTES;
	public String WEBCAMPAIGN;
	public String WEBMEDIUM;
	public String WEBKEYWORD;
	public int Priority;
	public int ERPOrderTypeID;
	public int DEALPRICE;
	public int OrderWebTypeID;
	public String OUTPRODUCTDATE;
	public boolean IsSubmitBuy;
	public boolean IsSendSMS;
	public int StatusID;
	public int SALEORDERID;
	public String CreateUser;
	public String CreateFullName;
	public int Sourceid;
	public String Fullname;
	public String Address;
	public String BillAddress;
	public String ShippAddress;
	public String Email;
	public String Phone;
	public String PersonalID;
	public String Note;
	public int Gender;
	public int ContactGender;
	public String Birthdate;
	public String TaxNo;
	public String OrderCode;
	public int StoreID;
	public int CountryID;
	public int ProvinceID;
	public int DistrictID;
	public int Payment;
	public int Delivery;
	public int ShippingCost;
	public int CurrencyUnit;
	public int CurrencyExchange;
	public String AccountSecretInfo;
	public String CouponCode;
	public int CouponDiscount;
	public String OWNERBANKNAME;
	public String EXPIRATIONDATEBANKACC;
	public String OutsideOrderID;
	public int TemporaryProvince;
	public int ResidenceProvince;
	public boolean lISKT3;
	public int ResidentDistrictID;
	public String CareeStatusCode;
	public int CompanyPartnerID;
	public String SourceOrder;
	public int Price;
	public int Quantity;
	public String SaleOrderNote;
	public int PrepaidAmount;
	public String Productcode;
	public String IMEI;
	public int RepaymentMount;
	public int PREPAIDPERCENT;
	public int REPAYMENTMONTH;
	public int REPAYMENTMONTHAMOUNT;
	public int Companyid;
	public String RepaymentProgramCode;
	public int ProgramID;
	public String SOURCECODE;
	public String CONTACTNAME;
	public String CONTACTMOBILE;
	public String CONTACTEMAIL;
	public int SHIPCITY;
	public int SHIPSTATE;
	public int SHIPWARDID;
	public int REFSALEPROGRAMID;
	public int GENCOMPANYID;
	public String TIMEEXPECTDELIVERY;
	public int OUTPUTSTOREID;
	public int PAYMENTSTATUS;
	public String TRANSACTIONID;
	public int TRANSACTIONTYPE;
	public String PAYMENTMETHOD;
	public String LOCALDATE;
	public String ORDERDESC;
	public String CLIENTIP;
	public int TOTALPAID;
	public int DISCOUNT;
	public int DISCOUNTREASONID;
	PromotionOrder[] LstPromotionOrder;
	PromotionDiscout[] lstPromotionDiscout;
	WebCoupon[] lstWebCoupon;
	GiftVoucher[] lstGiftVoucher;
	public String ProcessUser;
	public boolean IsNotify;
	public float DELIVERYTYPEID;
	public String STAFFUSER;
	public String STAFFUSERNOTE;
	public int STAFFSTATUSID;
	public String PERSONALIDHOUSE;
	public int CONFIRMSMS;
	public int AIRTIMETRANSACTIONTYPEID;
	public int REALINTERESTRATE;
	public int FLATINTERESTRATE;
	public int COLLECTIONFEE;
	public int INSUREFEE;
	public int PAPERSTYPEID;
	public int PAPERFEE;
	public float ISCONFIRM;
	public String GUARANTEEPHONE;
	public String RELATIVEPHONE;
	public int ACCOUNTVUIVUIID;
	public int SHIPADDRESSID;
	public int ISGETPROMOTIONSALEORDER;
	public String INSTALLMENTINFO;
	public String CARTTOKEN;
	public int PayableTypeID;
	String[] ListMemberPointDetailVV;
	public int CustomerProvinceID;
	public int CustomerDistrictID;
	public String CustomerAddress;
	public int StorePreview;
	public String Accessories;
	LogNotDelivery[] ListLogNotDelivery;
	public int IsCheckCouponERP;
	public int OriginateStoreID;
	public int DifferenceAmount;
	public String INSTALLMENTEPOS;
	public int PGGroupID;
	public int CustomerRank;
	public int language;
	public String DELIVERYINFO;

}
