package com.crm.crmqueue.dto;

public class ProductWeb {
	public String PRODUCTCOMBOID;
	public String APPLYERPSODETAILID;
	public float AdjustPrice;
	public String AdjustPriceContent;
	public String AdjustPriceUser;
	public String DiscountCode;
	String[] LstPromotionProduct;
	public String SaleOrderDetailID;
	public String ApplySaleOrderDetailID;
	public String DeliveryTime;
	public String IMAGEURL;
	public float OUTPUTBRANDID;
	public float RetailPrice;
	public float MaingroupID;
	public float InvenStory;
	String[] LstPromotionCycle;
	public String PACKAGESTYPE;
	public float SALEPROGRAMID;
	public String APPLYPRODUCTNO;
	public float PROMOTIONLISTGROUPID;
	public float PROMOTIONID;
	public String PACKCONTENT;
	public float AMOUNT;
	public String ProductCode;
	public String ProductName;
	public float Quantity;
	public float CurrentQuantity;
	public float SalePrice;
	public String IMEI;
	public float PRICESUPPORT;
	public String PRICESUPPORTREASON;
	public float INVENTORYSTATUSID;
	public float ISGETPROMOTION;
	public float OUTPUTSTOREID;
	public String ProductIDRef;
	public boolean IsGift;
	public float IDCustomerGift;
	public float ORIGINALSALEPRICE;
	public float RETURNVALUE;
	public float IsProductRef;
	public float StandardSaleprice;
	public float StandardAreaSaleprice;
	public float ShipPackageType;
	public float ShippingCost;
	public float OrderTypeID;
	public float InputIMEIID;
	public String InvoiceNote;
	String[] ListPromotionEX;
	String[] ListCusPromotion;
	public float ProductWebStatus;
	public String ApplyERPSaleOrderID;
	public float TranferStoreID;
	public float TransportTypeID;
	public float DayTranfer;
	public String ExtendInfo;
	public float OutGroupID;
	public float SaleProgramTypeID;
	public float DeliveryTypeID;
	public float _subGroupID;
	public float DeliveryShippingCost;
	public float TransferShippingCost;

}
